//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PermissionControlSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class PermissionSystem
	{
		public virtual string SystemName
		{
			get;
			set;
		}

		/// <summary>
		/// 是否是公平模式，如果是，则个体必须遵从组织的权限控制规则
		/// </summary>
		public virtual bool IsEquityModel
		{
			get;
			set;
		}

		public virtual IEnumerable<IPermission> Permissions
		{
			get;
			set;
		}

		public virtual IEnumerable<Role> Roles
		{
			get;
			set;
		}

        ///// <summary>
        ///// 添加权限
        ///// </summary>
        ///// <param name="permission">权限</param>
        //public virtual bool AddPermission(IPermission permission)
        //{
        //    throw new System.NotImplementedException();
        //}

        ///// <summary>
        ///// 移除权限
        ///// </summary>
        ///// <param name="permission">权限</param>
        //public virtual bool RemovePermission(IPermission permission)
        //{
        //    throw new System.NotImplementedException();
        //}

        ///// <summary>
        ///// 添加角色
        ///// </summary>
        ///// <param name="role">角色</param>
        //public virtual bool AddRole(Role role)
        //{
        //    throw new System.NotImplementedException();
        //}

        ///// <summary>
        ///// 移除角色
        ///// </summary>
        ///// <param name="role">角色</param>
        //public virtual bool RemoveRole(Role role)
        //{
        //    throw new System.NotImplementedException();
        //}

        ///// <summary>
        ///// 获取访问者是否拥有权限
        ///// </summary>
        ///// <param name="visitor">访问者</param>
        //public virtual IPermission GetPermission(IVisitor visitor)
        //{
        //    throw new System.NotImplementedException();
        //}

	}
}

