//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UserSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using PermissionControlSystem;

    public partial class User : IUser
	{
		public virtual IEnumerable<UserGroup> AtGroups
		{
			get;
			set;
		}

       
    }
}

