//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FileSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class File : IFileSystem
	{
		/// <summary>
		/// 文件类型
		/// </summary>
		public virtual string FileType
		{
			get;
			set;
		}

      

     
        ///// <summary>
        ///// 构造函数
        ///// </summary>
        ///// <param name="name">文件名</param>
        //public File(string name)
        //{
        //}

       
	}
}

