//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace UserSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract partial class UserGroup : IUser
	{
		public virtual IEnumerable<UserGroup> ChildGroups
		{
			get;
			private set;
		}

		public virtual IEnumerable<User> ChildUsers
		{
			get;
			private set;
		}

		/// <summary>
		/// 增加子用户
		/// </summary>
		/// <param name="user">用户</param>
		public virtual void AddUser(User user)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 增加子用户组
		/// </summary>
		/// <param name="group">用户组</param>
		public virtual void AddChildGroup(UserGroup group)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 移除用户
		/// </summary>
		/// <param name="user">所属的用户</param>
		public virtual void RemoveUser(User user)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 移除子用户组
		/// </summary>
		/// <param name="group">子用户组</param>
		public virtual void RemoveChildGrooup(UserGroup group)
		{
			throw new System.NotImplementedException();
		}

	}
}

