//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace FileSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Directory : IFileSystem
	{
		public virtual IEnumerable<File> ChildFiles
		{
			get;
			set;
		}

		public virtual IEnumerable<Directory> ChildDirectorys
		{
			get;
			set;
		}

		/// <summary>
		/// 增加文件
		/// </summary>
		/// <param name="file">文件</param>
		public virtual bool AddFile(File file)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 增加目录
		/// </summary>
		/// <param name="dir">目录</param>
		public virtual bool AddDirector(Directory dir)
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">目录名称</param>
		public Directory(string name)
		{
		}

	}
}

