//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PermissionControlSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPermission 
	{
		/// <summary>
		/// 拥有许可或者禁止
		/// </summary>
		bool IsOwner { get;set; }

		string PermissionName { get;set; }

		IEnumerable<IVisitor> Visitors { get;set; }

		IOperation IOperation { get;set; }

		IResource IResource { get;set; }

	}
}

