//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PermissionControlSystem
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 资源也是通常意义上的权限单元拥有的操作，
	/// </summary>
	public interface IOperation 
	{
		string OperationName { get;set; }
        object[] Parameters { get; set; }
        object Execute();
	}
}

